### ISSUE TITLE
Not getting Pair request on Atag One thermostat

### ISSUE THREAD

**Issue by aukedejong** [MatsNl/pyatag-ha#4]
Hi,

Running HA 0.101.1
Installed this integration with HACS.
Added atag: to the configuration.
Tried it with and without host: [ip] config.

Keep getting this log message:
2019-11-01 20:48:06 WARNING (MainThread) [pyatag.gateway] No status returned from ATAG One
2019-11-01 20:48:06 WARNING (MainThread) [pyatag.gateway] Atag not paired!
{'pair_reply': {'seqnr': 1, 'acc_status': 0}}
2019-11-01 20:48:06 ERROR (MainThread) [pyatag.gateway] Pairing failed - please confirm pairing on device

Nothing shows on the Atag One. Only the current room temperature, as always.

You know how to fix this? Did I forget something?

Thanks.
Auke de Jong

**Comment by MatsNl** [comment]
Can you show your full config? also try adding the emailaddress you used when registering on the atag portal, looks like it doesnt approve the pair request.

**Comment by aukedejong** [comment]
Changed config to this:

```
atag:
  host: 192.168.1.232
  email: aukedejong@gmail.com
  interface: eth0
```

I'm getting a different error message now.

```
2019-11-02 16:00:15 ERROR (MainThread) [pyatag.gateway] Pairing failed
Pairmsg: {'pair_message': {'seqnr': 1, 'account_auth': {'user_account': 'aukedejong@gmail.com', 'mac_address': 'B8:27:EB:08:3F:04'}, 'accounts': {'entries': [{'user_account': 'aukedejong@gmail.com', 'mac_address': 'B8:27:EB:08:3F:04', 'device_name': 'hassio', 'account_type': 1}]}}}
Error: [Errno None] Can not write request body for http://192.168.1.232:10000/pair
2019-11-02 16:00:15 ERROR (MainThread) [pyatag.gateway] Pairing failed - please confirm pairing on device
```

I can ping the IP address from my RaspPi, running HA.
It's the IP address that the Atag One shows on the Information screen.
And still no Pairing request on the Atag One.

You want to see my complete config? It's quit big.

Thanks.

**Comment by aukedejong** [comment]
It's working.
I'm not sure what fixed it. Maybe the email and/or the interface part.

But still no pair request.
Maybe because I used an other ATAG plugin before yours. Pair based on MAC address?

Thanks for you help and the great work!!
